db.createCollection("users");
db.createCollection("products");
db.createCollection("reservations");
db.createCollection("rooms");
db.createCollection("shops");
db.createCollection("events");
db.createCollection("requestsReservation");
db.createCollection("requestsEvent");
db.createCollection("reviews");